// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.5.1"
        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.33.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

def publishedGroup = findProperty("GROUP") ?: "com.github.498953584.quickjs-wrapper"
def publishedVersion = findProperty("VERSION_NAME") ?: System.getenv("VERSION") ?: "3.2.3-interrupt.1"

allprojects {
    group = publishedGroup
    version = publishedVersion

    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    if (project.name != "app") {

        apply plugin: "com.vanniktech.maven.publish"

        mavenPublishing {
            if (project.hasProperty("signingInMemoryKey")) {
                signAllPublications()
            }

            pom {
                name = "QuickJS Wrapper"
                description = "Quickjs wrapper library for Android/JVM."
                inceptionYear = "2022"
                url = "https://github.com/498953584/quickjs-wrapper"
                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                        distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
                developers {
                    developer {
                        id = "HarlonWang"
                        name = "Harlon Wang"
                        url = "https://github.com/HarlonWang"
                    }
                }
                scm {
                    url = "https://github.com/498953584/quickjs-wrapper"
                    connection = "scm:git:https://github.com/498953584/quickjs-wrapper.git"
                    developerConnection = "scm:git:https://github.com/498953584/quickjs-wrapper.git"
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
