name: Verify Tagged Release

on:
  push:
    tags:
      - '**'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :wrapper-java:build :wrapper-android:assembleRelease --no-daemon
