name: Verify

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          profile: pixel_2
          script: ./gradlew :wrapper-java:build :wrapper-android:assembleRelease :wrapper-android:connectedDebugAndroidTest --no-daemon
